{{- if .Values.pipelineConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opw.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ tpl (toYaml .Values.pipelineConfig) . | sha256sum }}
data:
  pipeline.yaml: | {{ tpl (toYaml .Values.pipelineConfig) . | nindent 4 }}
{{- end -}}
