args:
  - run
  - --skip-key-validation
  - --pipeline-config
  - "/etc/observability-pipelines-worker/pipeline.yaml"
extraContainers:
  - name: sleep
    image: busybox
    command: ['sh', '-c', "sleep 5"]
extraVolumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
extraVolumeMounts:
  - name: podinfo
    mountPath: "/etc/podinfo"
