args:
  - run
  - --skip-key-validation
  - --pipeline-config
  - "/etc/observability-pipelines-worker/pipelines.yaml"
initContainers:
  - name: sleep
    image: busybox
    command: ['sh', '-c', "sleep 5"]
  - name: touch
    image: busybox
    command:
    - touch
    - "/vector-data-dir/test"
    volumeMounts:
    - name: data
      mountPath: "/vector-data-dir"
