args:
  - run
  - --skip-key-validation
  - --pipeline-config
  - "/etc/observability-pipelines-worker/pipelines.yaml"
containerPorts:
  - name: override
    containerPort: 9999
    protocol: TCP
service:
  ports:
    - name: override
      port: 9999
      protocol: TCP
