args:
  - run
  - --skip-key-validation
  - --pipeline-config
  - "/etc/observability-pipelines-worker/pipelines.yaml"
pipelineConfig:
  sources:
    demo_logs:
      type: demo_logs
      format: json
  sinks:
    s3:
      type: aws_s3
      inputs: [demo_logs]
      bucket: logs-archive
      key_prefix: >-
        {{ print "{{kubernetes.pod_labels.\"app.kubernetes.io/client-id\"}}/%Y/%m/%d/{{kubernetes.pod_name}}/" }}
      compression: gzip
      encoding:
        codec: json
      region: us-east-1
